/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kurator_akka_interpreters_RInterpreter */

#ifndef _Included_org_kurator_akka_interpreters_RInterpreter
#define _Included_org_kurator_akka_interpreters_RInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kurator_akka_interpreters_RInterpreter
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_kurator_akka_interpreters_RInterpreter_run
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
